version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mlops-bootcamp

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - API_URL=http://fastapi:8000
    networks:
      - mlops-bootcamp

networks:
  mlops-bootcamp:
    driver: bridge
