# config/model_config.yaml
model:
  name: house_price_predictor
  version: 0.1.0
  type: regression
  algorithm: xgboost
  
hyperparameters:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  
features:
  - sqft
  - bedrooms
  - bathrooms
  - location
  - condition
  
target: price
